[project]
name = "abacus-sendtollm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "requests>=2.32.4",
    "types-requests>=2.32.4.20250809",
]
